server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Prueba
    username: postgres
    password: admin789
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update